#!/bin/bash

# docker run --rm --privileged -v $1:/tmp/v/land -v $2:/tmp/v/game.WAgame -v $(pwd)/wa.iso:/tmp/v/wa.iso zemke/docker-wa:latest getlog > $3 2> err.log

docker run -i --name waaas wa wa-getlog < $2 > $3
docker cp waaas:/root/.wine/drive_c/WA/DATA/land.dat $1
docker rm waaas

